
simulation:
  num_records: 1000
  input_range: [-1, 1]
  state_range: [-2, 2]
  output_range: [-1, 1]
  disturbance_range: [-0.5, 0.5]

system_parameters:
  A_range: [0.5, 1.5]
  B_range: [-0.5, 0.5]
  C_range: [-1, 1]
  D_range: [-0.5, 0.5]
